' LOAD ROUND MAP WHEN STARTING OR ENDING A ROUND
SUB LoadRoundMap(Round,CLR)
 LOCAL MA$,MB$
 PAGE WRITE 13
 MA$=RIGHT$("0"+STR$(Round*2+CLR),2)
 MB$=RIGHT$("0"+STR$(Round*2+CLR-1),2)
 LOAD PNG ".\IMAGES\MAPS\MAP"+MA$+".PNG",0,  0,1
 LOAD PNG ".\IMAGES\MAPS\MAP"+MB$+".PNG",0,101,1
 END SELECT
END SUB

' SHOW ROUND MAP WHEN STARTING OR ENDING A ROUND
SUB ShowRoundMap(M,Y)
 BLIT 0,M*101,32,Y,253,100,13,4
END SUB

